class Item {
  final int? id; // Nullable because it's auto-generated by SQLite
  final String name;
  final String description;
  final String imagePath; // Add imagePath here

  // Constructor
  Item({
    this.id,
    required this.name,
    required this.description,
    required this.imagePath, // Include imagePath in the constructor
  });

  // Convert an Item into a Map object (for saving to SQLite)
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'description': description,
      'imagePath': imagePath, // Save imagePath to database
    };
  }

  // Extract an Item object from a Map object (from SQLite query result)
  factory Item.fromMap(Map<String, dynamic> map) {
    return Item(
      id: map['id'],
      name: map['name'],
      description: map['description'],
      imagePath: map['imagePath'], // Retrieve imagePath from database
    );
  }
}
